global using System;
global using System.Collections.Generic;
global using System.Diagnostics;
global using System.IO;
global using System.Runtime.InteropServices;
global using System.Text;
global using System.Text.Json;
global using System.Text.Json.Serialization;
global using System.Threading;
global using System.Threading.Tasks;
global using PromptAssistant.Core.Abstractions;
global using Serilog;
global using ILogger = Serilog.ILogger;
