<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\PromptAssistant.Core\PromptAssistant.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Serilog" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="PromptAssistant.Cli.Tests" />
  </ItemGroup>
</Project>
