global using System;
global using System.Collections.Generic;
global using System.Collections.ObjectModel;
global using System.Diagnostics;
global using System.Linq;
global using System.Text;
global using System.Threading;
global using System.Threading.Tasks;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using Serilog;
global using ILogger = Serilog.ILogger;
global using PromptAssistant.Core.Abstractions;
global using PromptAssistant.Core.Models;
global using PromptAssistant.Core.Rendering;
